### ISSUE TITLE
where can i find update_data.R file?

### ISSUE THREAD

**Issue by liamxg** [Emergent-Epidemics/covid19_npi_china#1]
@scarpino @chiahungyang

**Comment by scarpino** [comment]
That's a legacy file that no longer runs because the data were taken down from Google sheets. I've updated the code so that you no longer need to run "build_data.R" and so that "case_map.R" will run without needing to run "build_data.R." We decided to leave the file "build_data.R" in place so that there's a record of how the data were processed.

**Comment by liamxg** [comment]
@scarpino thanks.

**Comment by liamxg** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/46078579/204078420-a2981b9e-5d95-4504-b7b0-bd3553677130.png">

**Comment by liamxg** [comment]
@scarpino  why my plot do not have the part that I below the red arrow?



<img width="289" alt="image" src="https://user-images.githubusercontent.com/46078579/204078442-d93f03cc-a9ea-4604-bc76-58622fdfd7e0.png">

**Comment by liamxg** [comment]
thanks.

**Comment by liamxg** [comment]
@scarpino @chiahungyang

**Comment by scarpino** [comment]
We added that just prior to publication because of a request from the journal to provide a complete map of the PRC. There's no data contained in that part of the figure. I can upload the shapefile we used to the repo.

**Comment by scarpino** [comment]
Ok, I pushed the shapefile.

**Comment by liamxg** [comment]
thanks. @scarpino
